export type Filter =
  | "all"
  | "virtual"
  | "today"
  | "weekend"
  | "food_and_drinks"
  | "exhibition"
  | "politics"
  | "music"
  | "health_awareness"
  | "sport"
  | "movie_night"
  | "seminar"
  | "carnival"
  | "games"
  | "talent_show"